
-- ORACLE (Part 1) --

--1

SELECT e.FIRST_NAME ,d.DEPARTMENT_NAME ,l.CITY 
FROM hr.EMPLOYEES e JOIN hr.DEPARTMENTS d
ON e.DEPARTMENT_ID  = d.DEPARTMENT_ID
JOIN hr.LOCATIONS l 
ON d.LOCATION_ID  = l.LOCATION_ID 
WHERE e.EMPLOYEE_ID  = 100;

--2

SELECT FIRST_NAME , LAST_NAME , HIRE_DATE , TO_CHAR( ADD_MONTHS(HIRE_DATE ,1),'DD') AS DateOfFirstDayOfSalary 
FROM HR.EMPLOYEES ;

--3

SELECT  e.LAST_NAME , e.SALARY ,d.DEPARTMENT_NAME , l.CITY 
FROM HR.EMPLOYEES e JOIN HR.DEPARTMENTS d 
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID 
JOIN hr.LOCATIONS l 
ON d.LOCATION_ID = l.LOCATION_ID 
WHERE d.DEPARTMENT_NAME = 'Purchasing' AND e.SALARY < 5000;

--4

SELECT e.DEPARTMENT_ID , d.DEPARTMENT_NAME, COUNT(e.EMPLOYEE_ID) "COUNT", AVG(E.SALARY) "AVG"    
FROM HR.DEPARTMENTS d
JOIN hr.EMPLOYEES e 
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
GROUP BY E.DEPARTMENT_ID , D.DEPARTMENT_NAME ;

--5

SELECT count(NVL2(MANAGER_ID,'true','false')) "Number Of Managers"
FROM hr.EMPLOYEES
GROUP BY NVL2(MANAGER_ID, 'true', 'false')
HAVING NVL2(MANAGER_ID, 'true', 'false') = 'true';

--6

SELECT e.FIRST_NAME ,e.LAST_NAME , l.CITY 
FROM hr.EMPLOYEES e JOIN hr.DEPARTMENTS d 
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID 
JOIN hr.LOCATIONS l 
ON l.LOCATION_ID = d.LOCATION_ID 
WHERE l.CITY = 'Southlake';

--7

SELECT e.LAST_NAME  , e.HIRE_DATE , e.SALARY, e2.EMPLOYEE_ID  "MANAGER" ,E2.HIRE_DATE  "MANAGER HIRE DATE"
FROM hr.EMPLOYEES e JOIN hr.EMPLOYEES e2 
ON e.MANAGER_ID = e2.EMPLOYEE_ID 
WHERE E.HIRE_DATE < E2.HIRE_DATE 

--8

SELECT e.FIRST_NAME ,d.DEPARTMENT_NAME
FROM HR.EMPLOYEES e JOIN HR.DEPARTMENTS d 
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID 
WHERE LOWER(SUBSTR(e.FIRST_NAME,1,1))  = LOWER( SUBSTR(e.FIRST_NAME,-1))  


--9

SELECT e.FIRST_NAME ,e.LAST_NAME , l.CITY 
FROM hr.EMPLOYEES e JOIN hr.DEPARTMENTS d 
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID 
JOIN hr.LOCATIONS l 
ON l.LOCATION_ID = d.LOCATION_ID 
WHERE l.CITY = 'Seattle' OR l.CITY = 'London' ;

--10

SELECT FIRST_NAME || ' ' || LAST_NAME "employee", SALARY 
FROM hr.EMPLOYEES e 
WHERE SALARY  BETWEEN 3500 AND 5000 AND DEPARTMENT_ID IN (10,60);

--11


SELECT e.first_name, e.last_name, e.salary
FROM hr.employees e
JOIN hr.departments d ON e.department_id = d.department_id
WHERE d.department_name = 'Accounting'
AND (EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM e.hire_date)) > 5

--12

SELECT
FIRST_NAME ,
LAST_NAME ,
(EXTRACT (YEAR FROM CURRENT_DATE ) - EXTRACT (YEAR FROM HIRE_DATE)) || ' YEAR ' || (EXTRACT (MONTH FROM CURRENT_DATE ) - EXTRACT (MONTH FROM HIRE_DATE)) || ' MONTH ' || (EXTRACT (DAY FROM CURRENT_DATE ) - EXTRACT (DAY FROM HIRE_DATE)) || ' DAY ' "EXPERIENCE" 
FROM HR.EMPLOYEES


--13

SELECT  LAST_NAME , (SALARY *12) + (SALARY * 12 * NVL(COMMISSION_PCT,0)) "ANNUAL SALARY"
FROM HR.EMPLOYEES e 


--14















