--1

SELECT ROUND(MAX(SALARY)) "MAXIMUM",ROUND(MIN(SALARY)) "MINIMUM", ROUND(SUM(SALARY)) "SUM", ROUND(AVG(SALARY)) "AVG" 
FROM HR.EMPLOYEES 

--2

SELECT JOB_ID , ROUND(MAX(SALARY)) "MAXIMUM",ROUND(MIN(SALARY)) "MINIMUM", ROUND(SUM(SALARY)) "SUM", ROUND(AVG(SALARY)) "AVG" 
FROM HR.EMPLOYEES 
GROUP BY JOB_ID 

--3

SELECT JOB_ID ,COUNT(*) 
FROM HR.EMPLOYEES 
GROUP BY JOB_ID 

--4

SELECT MANAGER_ID , COUNT(*) "NUMBER OF MANAGER"
FROM HR.EMPLOYEES 
GROUP BY MANAGER_ID 

--5

SELECT MAX(SALARY)-MIN(SALARY) "DIF"  
FROM HR.EMPLOYEES 

--6

SELECT e.MANAGER_ID , MIN(ee.SALARY)   
FROM HR.EMPLOYEES e, HR.EMPLOYEES ee 
GROUP BY e.MANAGER_ID, ee.SALARY
HAVING ee.SALARY > 6000
ORDER BY ee.SALARY  DESC


