--1

SELECT LOCATION_ID ,STREET_ADDRESS ,CITY ,STATE_PROVINCE ,COUNTRY_ID 
FROM  HR.LOCATIONS 
NATURAL JOIN HR.COUNTRIES

--2

SELECT last_name, department_id, department_name
FROM HR.employees
JOIN HR.departments
USING (department_id);


SELECT e.LAST_NAME ,d.DEPARTMENT_ID ,d.DEPARTMENT_NAME 
FROM HR.EMPLOYEES e ,HR.DEPARTMENTS d 

SELECT LAST_NAME 
FROM HR.EMPLOYEES
NATURAL JOIN HR.DEPARTMENTS;

--3

SELECT E.LAST_NAME , E.JOB_ID , E.DEPARTMENT_ID ,D.DEPARTMENT_NAME 
FROM HR.EMPLOYEES e JOIN HR.DEPARTMENTS d
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
JOIN HR.LOCATIONS l
ON d.LOCATION_ID = l.LOCATION_ID
WHERE LOWER(l.CITY) = 'toronto' ;

--4

SELECT w.LAST_NAME "Employee", w.EMPLOYEE_ID "Emp#", m.LAST_NAME "Manager" , m.EMPLOYEE_ID 
FROM hr.EMPLOYEES w JOIN HR.EMPLOYEES m
ON (w.MANAGER_ID  = m.EMPLOYEE_ID) ;

--5

SELECT w.LAST_NAME "Employee", w.EMPLOYEE_ID "Emp#", m.LAST_NAME "Manager" , m.EMPLOYEE_ID 
FROM hr.EMPLOYEES w left JOIN HR.EMPLOYEES m
ON (w.MANAGER_ID  = m.EMPLOYEE_ID) 
ORDER BY w.EMPLOYEE_ID  ASC ;



