--LEC5-LAB-2

--1

SELECT EMPLOYEE_ID ,LAST_NAME ,SALARY ,SALARY + (SALARY*15/100) AS EDITEDSALARY
FROM HR.EMPLOYEES;

--2

SELECT EMPLOYEE_ID ,LAST_NAME ,SALARY ,SALARY + (SALARY*15/100) AS NEWSALARY
FROM HR.EMPLOYEES;

--3

SELECT INITCAP(LAST_NAME) "FIRST_NAME_WITH_UPPERCASE",LENGTH(LAST_NAME) "LAST_NAME_LENGTH"
FROM HR.EMPLOYEES 
WHERE LAST_NAME LIKE 'J%'
OR LAST_NAME LIKE 'A%'
OR LAST_NAME LIKE 'M%';

--4

SELECT LAST_NAME , ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) "MONTH_WORKED",MONTHS_BETWEEN(SYSDATE, HIRE_DATE) "MONTH" , TRUNC(MONTHS_BETWEEN(SYSDATE, HIRE_DATE),2)
FROM HR.EMPLOYEES; 

--5

SELECT LAST_NAME ,LPAD(SALARY,15,'$') SALARY  
FROM HR.EMPLOYEES; 

--6

SELECT LAST_NAME, TRUNC((SYSDATE - HIRE_DATE)/7) as TENURE
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID = 90
ORDER  BY TENURE DESC;

--7


SELECT LAST_NAME || ' earns ' || SALARY || ' but he wants ' || SALARY*3 AS DreamSalary
FROM HR.EMPLOYEES 

--8

SELECT LAST_NAME ,HIRE_DATE,
	   NEXT_DAY(ADD_MONTHS(HIRE_DATE,6),'MONDAY') AS REWIEV
FROM HR.EMPLOYEES 

--9

SELECT LAST_NAME ,HIRE_DATE ,TO_CHAR(HIRE_DATE,'DAY') AS "DAY"
FROM HR.EMPLOYEES 

--10

SELECT LAST_NAME ,COMMISSION_PCT , NVL2(COMMISSION_PCT, COMMISSION_PCT ,'0') "XXX"
FROM HR.EMPLOYEES 

--11

SELECT FIRST_NAME ,LAST_NAME ,
	   DECODE(JOB_ID,'AD_PRES','A',
	   				 'ST_MAN','B',
	   				 'IT_PROG','C',
	   				 'SA_REP','D',
	   				 'SE_CLERK','E',
	   				 0)  "GRADE" 		
FROM HR.EMPLOYEES O

--12

SELECT FIRST_NAME ,LAST_NAME, JOB_ID,
		CASE JOB_ID WHEN 'AD_PRES' THEN 'A'
					WHEN 'ST_MAN' THEN 'B'
					WHEN 'IT_PROG' THEN 'C'
					WHEN 'SA_REP' THEN 'D'
					WHEN 'SE_CLERK' THEN 'E'
					ELSE '0' END "GRADE"
FROM HR.EMPLOYEES 












