--1

SELECT EMPLOYEE_ID ,LAST_NAME ,SALARY 
FROM HR.EMPLOYEES 
WHERE SALARY > (SELECT AVG(SALARY) FROM HR.EMPLOYEES)
ORDER BY SALARY ASC;

--2

SELECT EMPLOYEE_ID ,LAST_NAME 
FROM HR.EMPLOYEES 
WHERE DEPARTMENT_ID IS NOT NULL AND LAST_NAME LIKE '%u%';

SELECT employee_id, last_name
FROM hr.employees
WHERE department_id IN (SELECT department_id
                        FROM hr.employees
                        WHERE last_name like '%u%');
                       
                       
--3
                       
SELECT LAST_NAME ,DEPARTMENT_ID ,JOB_ID 
FROM HR.EMPLOYEES 
WHERE DEPARTMENT_ID  IN (SELECT DEPARTMENT_ID 
						FROM HR.DEPARTMENTS
						WHERE LOCATION_ID  = 1700 )
		

						
--4
						
SELECT LAST_NAME ,SALARY 
FROM HR.EMPLOYEES 
WHERE MANAGER_ID IN (SELECT EMPLOYEE_ID  FROM HR.EMPLOYEES WHERE LAST_NAME = 'King' )

--5

SELECT LAST_NAME , DEPARTMENT_ID ,JOB_ID 
FROM HR.EMPLOYEES e 
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID  FROM HR.DEPARTMENTS WHERE LOWER(DEPARTMENT_NAME)  = 'executive')

--6

SELECT  LAST_NAME 
FROM HR.EMPLOYEES
WHERE SALARY > ANY  (SELECT SALARY FROM HR.EMPLOYEES WHERE DEPARTMENT_ID = 60)

SELECT last_name FROM hr.employees
WHERE salary > ANY (SELECT salary
                    FROM hr.employees
                    WHERE department_id=60);


